services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - si_proj_sql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mariadb", "-h", "localhost", "-uroot", "-proot", "-e", "USE auth; SELECT COUNT(*) FROM access;"]
      interval: 5s
      timeout: 3s
      retries: 10

  mongodb:
    image: mongo:latest
    volumes:
      - si_proj_nosql:/data/db

  authapi:
    build:
      context: ./authapi
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_ROOT_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  studentapi:
    build: 
      context: ./studentapi
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_ROOT_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  messageapi:
    build: 
      context: ./messagesapi
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  coreapi:
    build:
      context: ./expressApi
    ports:
      - "8080:3000"
    depends_on:
      - authapi
      - messageapi
      - studentapi

  front:
    build:
      context: ./front
    ports:
      - "80:3000"

volumes:
  si_proj_nosql:
  si_proj_sql:
