services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - si_proj_sql:/var/lib/mysql

  mongodb:
    image: mongo:latest
    volumes:
      - si_proj_nosql:/data/db
    ports:
      - "27017:27017"

  authapi:
    build:
      context: ./authapi
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_ROOT_PASSWORD=root
    depends_on:
      - db
    ports:
      - "8080:8080"

  studentapi:
    build: 
      context: ./studentapi
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_ROOT_PASSWORD=root
    depends_on:
      - db
    ports:
      - "8081:8080"

  messageapi:
    build: 
      context: ./messagesapi
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb
    ports:
      - "8082:8080"

volumes:
  si_proj_nosql:
  si_proj_sql:
