services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - si_proj_sql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mariadb", "-h", "localhost", "-uroot", "-proot", "-e", "USE auth; SELECT COUNT(*) FROM access;"]
      interval: 5s
      timeout: 3s
      retries: 10

  mongodb:
    image: mongo:latest
    volumes:
      - si_proj_nosql:/data/db

  authapi:
    image: walkloly/projet-si:authapi
    build:
      context: ./authapi
    depends_on:
      db:
        condition: service_healthy

  studentapi:
    image: walkloly/projet-si:studentapi
    build: 
      context: ./studentapi
    depends_on:
      db:
        condition: service_healthy

  messageapi:
    image: walkloly/projet-si:messageapi
    build: 
      context: ./messagesapi
    depends_on:
      - mongodb

  coreapi:
    image: walkloly/projet-si:coreapi
    build:
      context: ./expressApi
    ports:
      - "8080:3000"
    depends_on:
      - authapi
      - messageapi
      - studentapi

  front:
    image: walkloly/projet-si:front
    build:
      context: ./front
    ports:
      - "80:3000"
    depends_on:
      - coreapi

volumes:
  si_proj_nosql:
  si_proj_sql:
