services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - si_proj_sql:/var/lib/mysql

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - si_proj_nosql:/data/db

  authapi:
    build:
      context: ./authapi
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_ROOT_PASSWORD=root
    depends_on:
      - db

  studentapi:
    build: 
      context: ./studentapi
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_ROOT_PASSWORD=root
    depends_on:
      - db

  messageapi:
    build: 
      context: ./messagesapi
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

volumes:
  si_proj_nosql:
  si_proj_sql: